# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a553f4b0db29eb54cf8072ed983a93e6643a72ab3d812ec00031b7258d2bfe0f2502ed64137f72484917f0e84b32c5c2f8e5a550261f0e6a26c613cfd4713cf

test:
  secret_key_base: 9ebe32d0bef94a19013f50cfdf8adf72c2fa62b6cda6817cf8caa8a361d5377d184a02d8567eb18c49eb7a38a98b816b93037d4c0d88d028888bcda3e264cedf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
